### ISSUE TITLE
i can not use in Windows

### ISSUE THREAD

**Issue by auosun** [jkotra/wpc#3]
i can not use it in Windows.I need a better README.md please .Thank you

**Comment by jkotra** [comment]
are you trying to build?

please describe your problem.

anyway, a small bug with wallheaven has been fixed in ba2b3e2774b06c22539c2c0881f5ef022a457f0e

you can download `wpc.exe` from [Releases](https://github.com/jkotra/wpc/releases/tag/0.1.4)
