### ISSUE TITLE
Clarify meaning of timers

### ISSUE THREAD

**Issue by Rekrii** [jkotra/wpc#6]
Possibly worth clarifying the meaning of the timers.

My current understanding: 
"--directory", does this only get used if the '--local' flag is present? or does it save all imgs here?
"--interval", default 60 seconds, will change the wall paper on this timer
"--maxage", default 'off' (-1 days), changer will stop using wallpapers older than this
"--update", default 120 seconds, will check bing/WH website for new wallpapers on this timer

If my understanding is correct, the idea of 'sane defaults' could apply here - I'd expect checking every 2 minutes, and changing every minute is a bit over the top. Could easily extend it by a factor of 50+. Changing every hour, and checking every day would be sensible.

**Comment by jkotra** [comment]
Thanks for your suggestions @Rekrii 

`--directory` is absolute. all images are saved to this directory. 
if neither `-w` nor `-b` is chosen, `--local` flag is set to `True`. 
https://github.com/jkotra/wpc/blob/fcc6be9fbdf537a556f62ae3e0063638230e0053/src/main.rs#L69

ex:
`-w` = only wallheaven images are considered.
`-w` and `--local` = wallheaven images and local images in `--directory` folder.

if bing `-b` is used, interval is set to 24hrs.
https://github.com/jkotra/wpc/blob/fcc6be9fbdf537a556f62ae3e0063638230e0053/src/main.rs#L105

I acknowledge the need for improvement in documentation and perhaps even a video tutorial, working on it.

I will consider changing defaults in next release.
